version: 2.1
jobs:
  build:
    docker:
      - image: dimtass/stm32-cde-image:latest
    steps:
      - checkout
      - run:
          name: Build firmware
          command: |
            git submodule sync;
            git submodule update --init --recursive;
            mkdir -p /tmp/artifacts;
            CLEANBUILD=true USE_DBGUART=ON USE_STDPERIPH_DRIVER=ON SRC=src_stdperiph ./build.sh;
            cp build-stm32/src_stdperiph/stm32f303-cmake-template.bin /tmp/artifacts/stm32f303-cmake-template-stdperiph.bin;
            CLEANBUILD=true USE_DBGUART=ON USE_STDPERIPH_DRIVER=ON USE_FREERTOS=ON SRC=src_freertos ./build.sh;
            cp build-stm32/src_freertos/stm32f303-cmake-template.bin /tmp/artifacts/stm32f303-cmake-template-freertos.bin;
      
      - store_artifacts:
          path: /tmp/artifacts/stm32f303-cmake-template-stdperiph.bin
          destination: stm32f303-cmake-template-stdperiph.bin
    
      - store_artifacts:
          path: /tmp/artifacts/stm32f303-cmake-template-freertos.bin
          destination: stm32f303-cmake-template-freertos.bin